### ISSUE TITLE
Introducing a section for how to use with Kubernetes

### ISSUE THREAD

**Issue by kartiklunkad26** [steeltoeoss-incubator/spring-petclinic-microservices#6]
This is an amazing initiative. It's good to see a _complex-enough_ .NET project in the microservice world. Not enough of these out there. 

I see detailed sections of how to deploy this with Docker Compose, and how to create images for it. 

It'd be great to have a section for how to deploy this with Kubernetes! :)

**Comment by jkonicki** [comment]
Initial support for K8s is in #7
